name: Build & Deploy

on:
  push:
    branches: [main]

env:
  REACT_APP_BASE_API_URL: ${{ secrets.REACT_APP_BASE_API_URL }}
  REACT_APP_MAPBOX_PUBLIC_KEY: ${{ secrets.REACT_APP_MAPBOX_PUBLIC_KEY }}
  REACT_APP_SENTRY_URL: ${{ secrets.REACT_APP_SENTRY_URL }}

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build:client

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: client/build # The folder the action should deploy.

  lambdas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build:server
